/**
 * The "Browse by use case" index in README.md.
 *
 * The index is generated from the records and checked in CI, so that the front
 * page of this repository cannot say something the records do not. The rule
 * that matters: only a product whose listing state is public appears here.
 * Anything in preparation — drafted, machine-prepared, or waiting for a person
 * to verify it — has no line in the index, because appearing in the index of a
 * catalog like this one reads as a recommendation.
 */

import { PUBLIC_LISTING_STATES } from './rules.mjs';

export const START_MARKER = '<!-- generated:use-case-index start -->';
export const END_MARKER = '<!-- generated:use-case-index end -->';

const GENERATED_NOTE = `${START_MARKER}
<!-- Generated by scripts/catalog.mjs index --write. Do not edit by hand. -->`;

function serviceSummary(record) {
  const services = (record.deployment?.dependent_services ?? [])
    .filter((service) => service.required)
    .map((service) => service.name);
  return services.length > 0 ? services.join(', ') : 'none';
}

function line(record) {
  const state = record.states.listing_state === 'tested' ? 'Tested' : 'Experimental';
  const date = record.verification?.verified_at ?? 'unknown date';
  const slug = record.product.slug;
  const guide = record.deployment.guide_path;
  const parts = [
    `- **[${record.product.name}](catalog/projects/${slug}.json)** — ${state} ${date} · ${record.deployment.provider} · requires: ${serviceSummary(record)}`,
  ];
  if (guide) parts.push(`  - setup: [${guide}](${guide})`);
  parts.push(`  - review: [published JuryPress review](${record.review.review_url})`);
  if (record.deployment.route_url) {
    parts.push(`  - deploy: [${record.deployment.template_type.replace(/_/g, ' ')} route](${record.deployment.route_url}) — on your own account, at your own cost`);
  }
  return parts.join('\n');
}

/**
 * @param {object[]} records every product record, listed or not
 * @returns {string} the Markdown body between the markers, without the markers
 */
export function renderIndex(records) {
  const listed = records
    .filter((record) => PUBLIC_LISTING_STATES.includes(record?.states?.listing_state))
    .sort((a, b) => (a.product.name.toLowerCase() < b.product.name.toLowerCase() ? -1 : 1));

  if (listed.length === 0) {
    return [
      '*No products are listed yet.*',
      '',
      'This section is generated from `catalog/projects/`. A product appears here',
      'only once a person has deployed it, every required check is answered, and the',
      'listing has been approved — see [docs/governance.md](docs/governance.md).',
      'Drafts and machine-prepared entries never appear here.',
    ].join('\n');
  }

  const groups = new Map();
  for (const record of listed) {
    const useCase = record.discovery.use_cases[0];
    if (!groups.has(useCase)) groups.set(useCase, []);
    groups.get(useCase).push(record);
  }

  const sections = [...groups.keys()].sort().map((useCase) => {
    const body = groups.get(useCase).map(line).join('\n');
    return `### ${useCase}\n\n${body}`;
  });

  return sections.join('\n\n');
}

/**
 * Replace the generated section of a README body.
 *
 * @param {string} readme current file contents
 * @param {string} body output of renderIndex()
 */
export function applyIndex(readme, body) {
  const start = readme.indexOf(START_MARKER);
  const end = readme.indexOf(END_MARKER);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`README.md is missing the ${START_MARKER} / ${END_MARKER} markers`);
  }
  const before = readme.slice(0, start);
  const after = readme.slice(end + END_MARKER.length);
  return `${before}${GENERATED_NOTE}\n\n${body}\n\n${END_MARKER}${after}`;
}
